### ISSUE TITLE
Object doesn't have headers attr

### ISSUE THREAD

**Issue by anonymousx97** [dmytrostriletskyi/threads-net#7]
https://github.com/dmytrostriletskyi/threads-net/blob/09922423bab5ab216f8b3b0f6f84436e8644978a/threads/main.py#L161

File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/threads/main.py", line 161, in get_post
    headers=self.headers,
            ^^^^^^^^^^^^
AttributeError: 'Threads' object has no attribute 'headers'

**Comment by dmytrostriletskyi** [comment]
@anonymousx97, thank you for the issue! 👍 

But now I see that Thread API somehow change this endpoint and in general it does not work as it worked before. I will dive into investigation and fixes when have time.

By the way, you can test it on your own as well and give me info if it works for you — https://github.com/dmytrostriletskyi/threads-net/blob/main/examples/get_post.py

**Comment by anonymousx97** [comment]
@dmytrostriletskyi 
I'm getting request's json decoder errors on latest release of your Package.

But It's working on v0.0.3 of your package.

**Comment by dmytrostriletskyi** [comment]
@anonymousx97, should also work on v0.0.6 as well. But as I said, they changed getting a post API so the problem not in a bug, but rather in changes on their end. Yeah, currently things are unstable and would because `Threads API` under active development, etc.

**Comment by dmytrostriletskyi** [comment]
@anonymousx97, thanks for the help! 👍 

Now I have released v0.0.7 with the fix and it should work completely.

**Comment by anonymousx97** [comment]
@dmytrostriletskyi 
Yes it's fixed and working good now. Thanks for your work.

do you plan to add inbuilt shortcode to media_id conversion?

I'm currently using this to convert it before passing to your object, hope this helps:

https://stackoverflow.com/a/43877227

**Comment by dmytrostriletskyi** [comment]
> do you plan to add inbuilt shortcode to media_id conversion?
Yes.

Thanks for the reference, will take a look.
